############# English navigation ##############

# main menu
[[main]]
name = "Field Manuals"
url = "/blog"
weight = 1

[[main]]
name = "Learning Tracks"
url = "/series"
weight = 2

[[main]]
name = "Pulse"
url = "/pulse"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Field Manuals"
url = "/blog"
weight = 2

[[footer]]
name = "Learning Tracks"
url = "/series"
weight = 3

[[footer]]
name = "About"
url = "/about"
weight = 4

[[footer]]
name = "Contact"
url = "/contact"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 6

[[footer]]
name = "Terms of Service"
url = "/terms-of-service"
weight = 7

[[footer]]
name = "Cookie Policy"
url = "/cookie-policy"
weight = 8
