############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Pulse"
url = "/pulse"
weight = 2

[[main]]
name = "Series"
url = "/series"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "About"
url = "/about"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4

[[footer]]
name = "Terms of Service"
url = "/terms-of-service"
weight = 5

[[footer]]
name = "Cookie Policy"
url = "/cookie-policy"
weight = 6
